### PR TITLE
Auth In Redux for FAQ page

### PR DESCRIPTION
**Pull request by kennetpostigo**
Provide some light onto how to use JWT with redux and some helpful links.

### CODE REVIEW

**Comment by markerikson** [comment]
Looks like a good start.  Would appreciate it if you could rephrase the title as more of a "How can I..." or "Does Redux support...?" question, and format the links section the same as the other items in the page (sub-headings, link description formatting, etc).

**Comment by kennetpostigo** [comment]
Okay will do

**Comment by kennetpostigo** [comment]
Lmk if the title change is appropriate. Great Job on the FAQ page!

**Comment by markerikson** [comment]
Title looks better, but the links section still needs to be formatted to match the other entries.

**Comment by kennetpostigo** [comment]
okay Ill update now

**Comment by markerikson** [comment]
Awright, that should do for now.  Thanks for the addition!

**Comment by kennetpostigo** [comment]
No problem!

**Pull request merged**
