### PR TITLE
Fix wrong invocation of toggleTodo which should be editTodo

### PR DESCRIPTION
**Pull request by pgilad**

### CODE REVIEW

**Comment by markerikson** [comment]
Thanks for the fix!

**Comment by markerikson** [comment]
Would also appreciate any other comments you have on the overall content of the new pages so far, as well.

**Comment by pgilad** [comment]
So far great reads! I would love to see info about orchestrating nested resources. For example if I have a book and an author, and I can only know the author's name after I fetch the book, how can I make sure my component will have both book and author available?
How can I do this while showing loading indicators?
How to structure it with indexed lists?

**Comment by markerikson** [comment]
Hmm.  Most of that really doesn't have much to do with reducer structuring, really.

**Comment by pgilad** [comment]
I agree

**Comment by pgilad** [comment]
Suppose you have an entity named security alert which belongs to an organization.
How do you structure your reducer(s) in order to handle:
1. Fetching all organizations
2. Fetching all security alerts by an organization
3. Fetching a security alert before knowing the organization itself (i.e - flat router)

How do you maintain the state for loader indicating in each item?

Using your system from Normalizing State Shape:

``` js
{
    entities: {
        securityAlerts : { byId : {}, allIds : [], isFetching: false },
        organizations : { byId : {}, allIds : [], isFetching: false },
        securityAlertsByOrganization : {
            isFetching: false,
            fetchingIds: [],
            byId : {
                1 : {},
                2 : {}
            },
            allIds : [1, 2]
        }
    }
}
```

Or perhaps something like that. But maintaining that state is pretty difficult with multiple reducers (Some perhaps only getting a slice of the original state)

**Comment by markerikson** [comment]
Dynamic fetching and loading is admittedly something that I haven't had to deal with yet, so I don't have too much help to offer on that topic.

**Pull request merged**
